name: Update Glowing Badges
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Glowing Badges
        run: |
          mkdir -p assets

          # LinkedIn Badge
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="40">
            <defs>
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge>
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            <rect width="180" height="40" rx="8" ry="8" fill="#0077B5" filter="url(#glow)"/>
            <text x="50" y="25" font-size="18" fill="white" font-family="Arial, sans-serif">LinkedIn</text>
            <image href="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" x="10" y="5" height="30px"/>
          </svg>' > assets/linkedin-badge.svg

          # Twitter/X Badge
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="40">
            <defs>
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge>
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            <rect width="180" height="40" rx="8" ry="8" fill="#1DA1F2" filter="url(#glow)"/>
            <text x="50" y="25" font-size="18" fill="white" font-family="Arial, sans-serif">Twitter</text>
            <image href="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/twitter/twitter-original.svg" x="10" y="5" height="30px"/>
          </svg>' > assets/twitter-badge.svg

          # Gmail Badge
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="40">
            <defs>
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge>
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            <rect width="180" height="40" rx="8" ry="8" fill="#D44638" filter="url(#glow)"/>
            <text x="50" y="25" font-size="18" fill="white" font-family="Arial, sans-serif">Gmail</text>
            <image href="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg" x="10" y="5" height="30px"/>
          </svg>' > assets/gmail-badge.svg

      - name: Commit and Push Changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "actions@github.com"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/durgadaspatil45/durgadaspatil45.git
            git add assets/*.svg
            git commit -m "Update glowing badges" || echo "No changes to commit"
            git push origin master
